//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleBooksKJV
    {
        public int ID { get; set; }
        public string BookId { get; set; }
        public Nullable<int> ChapterId { get; set; }
        public Nullable<int> VerseId { get; set; }
        public string BodyText { get; set; }
    }
}
