//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleFootNote
    {
        public int ID { get; set; }
        public string Idx { get; set; }
        public string Content { get; set; }
        public string BookIdx { get; set; }
        public Nullable<int> ChapterIdx { get; set; }
        public Nullable<int> VerseIdx { get; set; }
        public string CompoKey { get; set; }
        public Nullable<int> BibleSeq { get; set; }
    }
}
