//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUser
    {
        public long Id { get; set; }
        public Nullable<long> BusinessId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string CellNumber { get; set; }
        public string UnlockCode { get; set; }
        public string BackupCellNumber { get; set; }
        public string UUID { get; set; }
        public string CompanyCodePrimary { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
