//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chapter
    {
        public int chapter_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> chapter_number { get; set; }
        public string chapter_title { get; set; }
        public string chapter_content { get; set; }
    
        public virtual book book { get; set; }
    }
}
