//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesLink
    {
        public string Idx { get; set; }
        public int idFiles { get; set; }
        public Nullable<int> fSorted { get; set; }
    }
}
