//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int id { get; set; }
        public string fName { get; set; }
        public string fNamePath { get; set; }
        public string fComment { get; set; }
        public string fType { get; set; }
        public string fExported { get; set; }
        public string fThumbs { get; set; }
    }
}
