//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public string Idx { get; set; }
        public string Body { get; set; }
        public string Meaning { get; set; }
        public string Title { get; set; }
        public string AFirst { get; set; }
        public string Busy { get; set; }
        public string CategoryN { get; set; }
        public int Id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> StatusFlag { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string currentStatus { get; set; }
    }
}
