//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciprocalSeeMainRef
    {
        public int id { get; set; }
        public string Idx { get; set; }
        public string Link { get; set; }
        public string Title { get; set; }
        public string CategoryN { get; set; }
        public string CatFlag { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
