//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_detail
    {
        public int Idx { get; set; }
        public System.DateTime Update_date { get; set; }
        public string Update_detail { get; set; }
        public int Id { get; set; }
    }
}
