//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_master
    {
        public float Idx { get; set; }
        public string Request_name { get; set; }
        public System.DateTime Date_req { get; set; }
        public Nullable<System.DateTime> Date_fin { get; set; }
        public int Id { get; set; }
    }
}
