//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    
    public partial class sp_EmptyReferencesDetails_Result1
    {
        public int id { get; set; }
        public string Idx { get; set; }
        public string body { get; set; }
        public string Title { get; set; }
        public string CategoryN { get; set; }
        public string currentStatus { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
