//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string nKey { get; set; }
        public string Date_last { get; set; }
        public string Time_last { get; set; }
        public string Date_added { get; set; }
        public int ID { get; set; }
        public string categoryN { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
