//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cugonlineWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int ID { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string TimeIn { get; set; }
        public string Reference { get; set; }
        public string Edited { get; set; }
        public string Uploaded { get; set; }
        public string Attachment { get; set; }
        public string Deleted { get; set; }
        public int UserActivitiesID { get; set; }
        public Nullable<int> AttachmentId { get; set; }
    }
}
